name: Test plausibility and completeness

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.2"
      - name: Install dependencies
        run: |
          poetry install --sync --with=dev
      - name: Test with pytest
        run: |
          poetry run poe test-ci
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: junit/test-results.xml
          summary: true
          fail-on-empty: true
          title: Test results
